variable "PROJECT_ID" {}
variable "PROJECT_FOLDER_ID" {}
variable "ORGANIZATION_ID" {}
variable "BILLING_ACCOUNT" {}
variable "REGION" {}
variable "ZONE" {}
variable "ACCOUNT" {}
variable "SA_NAME" {}
variable "CREDS" {}
variable "BUCKET" {}
